name: 🧩 Update GitHub Profile Summary Cards

on:
  schedule:
    # Ejecutar cada 24 horas
    - cron: "0 */24 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate GitHub Profile Summary Cards
    permissions:
      contents: write

    steps:
      - name: 🔹 Checkout repository
        uses: actions/checkout@v4

      - name: 🔹 Generate profile summary cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.SUMMARY_GITHUB_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
          BRANCH_NAME: "main"
          UTC_OFFSET: -5  # Cambia según tu zona horaria (Ecuador = -5)
          AUTO_PUSH: true
